### ISSUE TITLE
Plugin will always prioritize offhand shulkers

### ISSUE THREAD

**Issue by Novasky-Guy** [eyrond/eShulker#1]
**Description**:
When someone is holding a shulker in their offhand aswell as their main hand, the plugin will always prioritize opening the offhand shulker, causing unneccary clicks or offhand switches.

**Expected**:
The plugin should detect that someone is holding a shulker in their main hand and prioritize that instead of their offhand shulker.

**Server version**:
This server is running Paper version git-Paper-540 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: f9f9079)
You are running the latest version
Previous version: git-Paper-307 (MC: 1.19.2)

**Plugin version**:
Latest version from https://hangar.papermc.io/eyrond/eShulker

**Proof**:
https://github.com/eyrond/eShulker/assets/91095629/20b97686-4960-4c8b-a439-cda3ebc1eec0

**Comment by M0diis** [comment]
Where's the PR

**Comment by eyrond** [comment]
Fixed in 2c65765a29191b3d218fce445ef1429083c218c1. Update will be delivered in 1.0.1.
